const Countries = [
    { no: 1, label: 'Afghanistan', code: 'AF', value: '+93' },
    { no: 2, label: 'Albania', code: 'AL', value: '+355' },
    { no: 3, label: 'Algeria', code: 'DZ', value: '+213' },
    { no: 4, label: 'American Samoa', code: 'AS', value: '+1684' },
    { no: 5, label: 'Andorra', code: 'AD', value: '+376' },
    { no: 6, label: 'Angola', code: 'AO', value: '+244' },
    { no: 7, label: 'Anguilla', code: 'AI', value: '+1264' },
    { no: 8, label: 'Antarctica', code: 'AQ', value: '+672' },
    { no: 9, label: 'Antigua and Barbuda', code: 'AG', value: '+1268' },
    { no: 10, label: 'Argentina', code: 'AR', value: '+54' },
    { no: 11, label: 'Armenia', code: 'AM', value: '+374' },
    { no: 12, label: 'Aruba', code: 'AW', value: '+297' },
    { no: 13, label: 'Australia', code: 'AU', value: '+61' },
    { no: 14, label: 'Austria', code: 'AT', value: '+43' },
    { no: 15, label: 'Azerbaijan', code: 'AZ', value: '+994' },
    { no: 16, label: 'Bahamas', code: 'BS', value: '+1242' },
    { no: 17, label: 'Bahrain', code: 'BH', value: '+973' },
    { no: 18, label: 'Bangladesh', code: 'BD', value: '+880' },
    { no: 19, label: 'Barbados', code: 'BB', value: '+1246' },
    { no: 20, label: 'Belarus', code: 'BY', value: '+375' },
    { no: 21, label: 'Belgium', code: 'BE', value: '+32' },
    { no: 22, label: 'Belize', code: 'BZ', value: '+501' },
    { no: 23, label: 'Benin', code: 'BJ', value: '+229' },
    { no: 24, label: 'Bermuda', code: 'BM', value: '+1441' },
    { no: 25, label: 'Bhutan', code: 'BT', value: '+975' },
    { no: 26, label: 'Bolivia', code: 'BO', value: '+591' },
    { no: 27, label: 'Bosnia and Herzegovina', code: 'BA', value: '+387' },
    { no: 28, label: 'Botswana', code: 'BW', value: '+267' },
    { no: 29, label: 'Brazil', code: 'BR', value: '+55' },
    { no: 30, label: 'British Indian Ocean Territory', code: 'IO', value: '+246' },
    { no: 31, label: 'British Virgin Islands', code: 'VG', value: '+1284' },
    { no: 32, label: 'Brunei', code: 'BN', value: '+673' },
    { no: 33, label: 'Bulgaria', code: 'BG', value: '+359' },
    { no: 34, label: 'Burkina Faso', code: 'BF', value: '+226' },
    { no: 35, label: 'Burundi', code: 'BI', value: '+257' },
    { no: 36, label: 'Cambodia', code: 'KH', value: '+855' },
    { no: 37, label: 'Cameroon', code: 'CM', value: '+237' },
    { no: 38, label: 'Canada', code: 'CA', value: '+1' },
    { no: 39, label: 'Cape Verde', code: 'CV', value: '+238' },
    { no: 40, label: 'Cayman Islands', code: 'KY', value: '+1345' },
    { no: 41, label: 'Central African Republic', code: 'CF', value: '+236' },
    { no: 42, label: 'Chad', code: 'TD', value: '+235' },
    { no: 43, label: 'Chile', code: 'CL', value: '+56' },
    { no: 44, label: 'China', code: 'CN', value: '+86' },
    { no: 45, label: 'Christmas Island', code: 'CX', value: '+61' },
    { no: 46, label: 'Cocos Islands', code: 'CC', value: '+61' },
    { no: 47, label: 'Colombia', code: 'CO', value: '+57' },
    { no: 48, label: 'Comoros', code: 'KM', value: '+269' },
    { no: 49, label: 'Cook Islands', code: 'CK', value: '+682' },
    { no: 50, label: 'Costa Rica', code: 'CR', value: '+506' },
    { no: 51, label: 'Croatia', code: 'HR', value: '+385' },
    { no: 52, label: 'Cuba', code: 'CU', value: '+53' },
    { no: 53, label: 'Curacao', code: 'CW', value: '+599' },
    { no: 54, label: 'Cyprus', code: 'CY', value: '+357' },
    { no: 55, label: 'Czech Republic', code: 'CZ', value: '+420' },
    { no: 56, label: 'Democratic Republic of the Congo', code: 'CD', value: '+243' },
    { no: 57, label: 'Denmark', code: 'DK', value: '+45' },
    { no: 58, label: 'Djibouti', code: 'DJ', value: '+253' },
    { no: 59, label: 'Dominica', code: 'DM', value: '+1767' },
    { no: 60, label: 'Dominican Republic', code: 'DO', value: '+1809' },
    { no: 61, label: 'Dominican Republic', code: 'DO', value: '+1829' },
    { no: 62, label: 'Dominican Republic', code: 'DO', value: '+1849' },
    { no: 63, label: 'East Timor', code: 'TL', value: '+670' },
    { no: 64, label: 'Ecuador', code: 'EC', value: '+593' },
    { no: 65, label: 'Egypt', code: 'EG', value: '+20' },
    { no: 66, label: 'El Salvador', code: 'SV', value: '+503' },
    { no: 67, label: 'Equatorial Guinea', code: 'GQ', value: '+240' },
    { no: 68, label: 'Eritrea', code: 'ER', value: '+291' },
    { no: 69, label: 'Estonia', code: 'EE', value: '+372' },
    { no: 70, label: 'Ethiopia', code: 'ET', value: '+251' },
    { no: 71, label: 'Falkland Islands', code: 'FK', value: '+500' },
    { no: 72, label: 'Faroe Islands', code: 'FO', value: '+298' },
    { no: 73, label: 'Fiji', code: 'FJ', value: '+679' },
    { no: 74, label: 'Finland', code: 'FI', value: '+358' },
    { no: 75, label: 'France', code: 'FR', value: '+33' },
    { no: 76, label: 'French Polynesia', code: 'PF', value: '+689' },
    { no: 77, label: 'Gabon', code: 'GA', value: '+241' },
    { no: 78, label: 'Gambia', code: 'GM', value: '+220' },
    { no: 79, label: 'Georgia', code: 'GE', value: '+995' },
    { no: 80, label: 'Germany', code: 'DE', value: '+49' },
    { no: 81, label: 'Ghana', code: 'GH', value: '+233' },
    { no: 82, label: 'Gibraltar', code: 'GI', value: '+350' },
    { no: 83, label: 'Greece', code: 'GR', value: '+30' },
    { no: 84, label: 'Greenland', code: 'GL', value: '+299' },
    { no: 85, label: 'Grenada', code: 'GD', value: '+1473' },
    { no: 86, label: 'Guam', code: 'GU', value: '+1671' },
    { no: 87, label: 'Guatemala', code: 'GT', value: '+502' },
    { no: 88, label: 'Guernsey', code: 'GG', value: '+441481' },
    { no: 89, label: 'Guinea', code: 'GN', value: '+224' },
    { no: 90, label: 'Guinea-Bissau', code: 'GW', value: '+245' },
    { no: 91, label: 'Guyana', code: 'GY', value: '+592' },
    { no: 92, label: 'Haiti', code: 'HT', value: '+509' },
    { no: 93, label: 'Honduras', code: 'HN', value: '+504' },
    { no: 94, label: 'Hong Kong', code: 'HK', value: '+852' },
    { no: 95, label: 'Hungary', code: 'HU', value: '+36' },
    { no: 96, label: 'Iceland', code: 'IS', value: '+354' },
    { no: 97, label: 'India', code: 'IN', value: '+91' },
    { no: 98, label: 'Indonesia', code: 'ID', value: '+62' },
    { no: 99, label: 'Iran', code: 'IR', value: '+98' },
    { no: 100, label: 'Iraq', code: 'IQ', value: '+964' },
    { no: 101, label: 'Ireland', code: 'IE', value: '+353' },
    { no: 102, label: 'Isle of Man', code: 'IM', value: '+441624' },
    { no: 103, label: 'Israel', code: 'IL', value: '+972' },
    { no: 104, label: 'Italy', code: 'IT', value: '+39' },
    { no: 105, label: 'Ivory Coast', code: 'CI', value: '+225' },
    { no: 106, label: 'Jamaica', code: 'JM', value: '+1876' },
    { no: 107, label: 'Japan', code: 'JP', value: '+81' },
    { no: 108, label: 'Jersey', code: 'JE', value: '+441534' },
    { no: 109, label: 'Jordan', code: 'JO', value: '+962' },
    { no: 110, label: 'Kazakhstan', code: 'KZ', value: '+7' },
    { no: 111, label: 'Kenya', code: 'KE', value: '+254' },
    { no: 112, label: 'Kiribati', code: 'KI', value: '+686' },
    { no: 113, label: 'Kosovo', code: 'XK', value: '+383' },
    { no: 114, label: 'Kuwait', code: 'KW', value: '+965' },
    { no: 115, label: 'Kyrgyzstan', code: 'KG', value: '+996' },
    { no: 116, label: 'Laos', code: 'LA', value: '+856' },
    { no: 117, label: 'Latvia', code: 'LV', value: '+371' },
    { no: 118, label: 'Lebanon', code: 'LB', value: '+961' },
    { no: 119, label: 'Lesotho', code: 'LS', value: '+266' },
    { no: 120, label: 'Liberia', code: 'LR', value: '+231' },
    { no: 121, label: 'Libya', code: 'LY', value: '+218' },
    { no: 122, label: 'Liechtenstein', code: 'LI', value: '+423' },
    { no: 123, label: 'Lithuania', code: 'LT', value: '+370' },
    { no: 124, label: 'Luxembourg', code: 'LU', value: '+352' },
    { no: 125, label: 'Macau', code: 'MO', value: '+853' },
    { no: 126, label: 'Macedonia', code: 'MK', value: '+389' },
    { no: 127, label: 'Madagascar', code: 'MG', value: '+261' },
    { no: 128, label: 'Malawi', code: 'MW', value: '+265' },
    { no: 129, label: 'Malaysia', code: 'MY', value: '+60' },
    { no: 130, label: 'Maldives', code: 'MV', value: '+960' },
    { no: 131, label: 'Mali', code: 'ML', value: '+223' },
    { no: 132, label: 'Malta', code: 'MT', value: '+356' },
    { no: 133, label: 'Marshall Islands', code: 'MH', value: '+692' },
    { no: 134, label: 'Mauritania', code: 'MR', value: '+222' },
    { no: 135, label: 'Mauritius', code: 'MU', value: '+230' },
    { no: 136, label: 'Mayotte', code: 'YT', value: '+262' },
    { no: 137, label: 'Mexico', code: 'MX', value: '+52' },
    { no: 138, label: 'Micronesia', code: 'FM', value: '+691' },
    { no: 139, label: 'Moldova', code: 'MD', value: '+373' },
    { no: 140, label: 'Monaco', code: 'MC', value: '+377' },
    { no: 141, label: 'Mongolia', code: 'MN', value: '+976' },
    { no: 142, label: 'Montenegro', code: 'ME', value: '+382' },
    { no: 143, label: 'Montserrat', code: 'MS', value: '+1664' },
    { no: 144, label: 'Morocco', code: 'MA', value: '+212' },
    { no: 145, label: 'Mozambique', code: 'MZ', value: '+258' },
    { no: 146, label: 'Myanmar', code: 'MM', value: '+95' },
    { no: 147, label: 'Namibia', code: 'NA', value: '+264' },
    { no: 148, label: 'Nauru', code: 'NR', value: '+674' },
    { no: 149, label: 'Nepal', code: 'NP', value: '+977' },
    { no: 150, label: 'Netherlands', code: 'NL', value: '+31' },
    { no: 151, label: 'Netherlands Antilles', code: 'AN', value: '+599' },
    { no: 152, label: 'New Caledonia', code: 'NC', value: '+687' },
    { no: 153, label: 'New Zealand', code: 'NZ', value: '+64' },
    { no: 154, label: 'Nicaragua', code: 'NI', value: '+505' },
    { no: 155, label: 'Niger', code: 'NE', value: '+227' },
    { no: 156, label: 'Nigeria', code: 'NG', value: '+234' },
    { no: 157, label: 'Niue', code: 'NU', value: '+683' },
    { no: 158, label: 'North Korea', code: 'KP', value: '+850' },
    { no: 159, label: 'Northern Mariana Islands', code: 'MP', value: '+1670' },
    { no: 160, label: 'Norway', code: 'NO', value: '+47' },
    { no: 161, label: 'Oman', code: 'OM', value: '+968' },
    { no: 162, label: 'Pakistan', code: 'PK', value: '+92' },
    { no: 163, label: 'Palau', code: 'PW', value: '+680' },
    { no: 164, label: 'Palestine', code: 'PS', value: '+970' },
    { no: 165, label: 'Panama', code: 'PA', value: '+507' },
    { no: 166, label: 'Papua New Guinea', code: 'PG', value: '+675' },
    { no: 167, label: 'Paraguay', code: 'PY', value: '+595' },
    { no: 168, label: 'Peru', code: 'PE', value: '+51' },
    { no: 169, label: 'Philippines', code: 'PH', value: '+63' },
    { no: 170, label: 'Pitcairn', code: 'PN', value: '+64' },
    { no: 171, label: 'Poland', code: 'PL', value: '+48' },
    { no: 172, label: 'Portugal', code: 'PT', value: '+351' },
    { no: 173, label: 'Puerto Rico', code: 'PR', value: '+1787' },
    { no: 174, label: 'Puerto Rico', code: 'PR', value: '+1939' },
    { no: 175, label: 'Qatar', code: 'QA', value: '+974' },
    { no: 176, label: 'Republic of the Congo', code: 'CG', value: '+242' },
    { no: 177, label: 'Reunion', code: 'RE', value: '+262' },
    { no: 178, label: 'Romania', code: 'RO', value: '+40' },
    { no: 179, label: 'Russia', code: 'RU', value: '+7' },
    { no: 180, label: 'Rwanda', code: 'RW', value: '+250' },
    { no: 181, label: 'Saint Barthelemy', code: 'BL', value: '+590' },
    { no: 182, label: 'Saint Helena', code: 'SH', value: '+290' },
    { no: 183, label: 'Saint Kitts and Nevis', code: 'KN', value: '+1869' },
    { no: 184, label: 'Saint Lucia', code: 'LC', value: '+1758' },
    { no: 185, label: 'Saint Martin', code: 'MF', value: '+590' },
    { no: 186, label: 'Saint Pierre and Miquelon', code: 'PM', value: '+508' },
    { no: 187, label: 'Saint Vincent and the Grenadines', code: 'VC', value: '+1784' },
    { no: 188, label: 'Samoa', code: 'WS', value: '+685' },
    { no: 189, label: 'San Marino', code: 'SM', value: '+378' },
    { no: 190, label: 'Sao Tome and Principe', code: 'ST', value: '+239' },
    { no: 191, label: 'Saudi Arabia', code: 'SA', value: '+966' },
    { no: 192, label: 'Senegal', code: 'SN', value: '+221' },
    { no: 193, label: 'Serbia', code: 'RS', value: '+381' },
    { no: 194, label: 'Seychelles', code: 'SC', value: '+248' },
    { no: 195, label: 'Sierra Leone', code: 'SL', value: '+232' },
    { no: 196, label: 'Singapore', code: 'SG', value: '+65' },
    { no: 197, label: 'Sint Maarten', code: 'SX', value: '+1721' },
    { no: 198, label: 'Slovakia', code: 'SK', value: '+421' },
    { no: 199, label: 'Slovenia', code: 'SI', value: '+386' },
    { no: 200, label: 'Solomon Islands', code: 'SB', value: '+677' },
    { no: 201, label: 'Somalia', code: 'SO', value: '+252' },
    { no: 202, label: 'South Africa', code: 'ZA', value: '+27' },
    { no: 203, label: 'South Korea', code: 'KR', value: '+82' },
    { no: 204, label: 'South Sudan', code: 'SS', value: '+211' },
    { no: 205, label: 'Spain', code: 'ES', value: '+34' },
    { no: 206, label: 'Sri Lanka', code: 'LK', value: '+94' },
    { no: 207, label: 'Sudan', code: 'SD', value: '+249' },
    { no: 208, label: 'Suriname', code: 'SR', value: '+597' },
    { no: 209, label: 'Svalbard and Jan Mayen', code: 'SJ', value: '+47' },
    { no: 210, label: 'Swaziland', code: 'SZ', value: '+268' },
    { no: 211, label: 'Sweden', code: 'SE', value: '+46' },
    { no: 212, label: 'Switzerland', code: 'CH', value: '+41' },
    { no: 213, label: 'Syria', code: 'SY', value: '+963' },
    { no: 214, label: 'Taiwan', code: 'TW', value: '+886' },
    { no: 215, label: 'Tajikistan', code: 'TJ', value: '+992' },
    { no: 216, label: 'Tanzania', code: 'TZ', value: '+255' },
    { no: 217, label: 'Thailand', code: 'TH', value: '+66' },
    { no: 218, label: 'Togo', code: 'TG', value: '+228' },
    { no: 219, label: 'Tokelau', code: 'TK', value: '+690' },
    { no: 220, label: 'Tonga', code: 'TO', value: '+676' },
    { no: 221, label: 'Trinidad and Tobago', code: 'TT', value: '+1868' },
    { no: 222, label: 'Tunisia', code: 'TN', value: '+216' },
    { no: 223, label: 'Turkey', code: 'TR', value: '+90' },
    { no: 224, label: 'Turkmenistan', code: 'TM', value: '+993' },
    { no: 225, label: 'Turks and Caicos Islands', code: 'TC', value: '+1649' },
    { no: 226, label: 'Tuvalu', code: 'TV', value: '+688' },
    { no: 227, label: 'U.S. Virgin Islands', code: 'VI', value: '+1340' },
    { no: 228, label: 'Uganda', code: 'UG', value: '+256' },
    { no: 229, label: 'Ukraine', code: 'UA', value: '+380' },
    { no: 230, label: 'United Arab Emirates', code: 'AE', value: '+971' },
    { no: 231, label: 'United Kingdom', code: 'GB', value: '+44' },
    { no: 232, label: 'United States', code: 'US', value: '+1' },
    { no: 233, label: 'Uruguay', code: 'UY', value: '+598' },
    { no: 234, label: 'Uzbekistan', code: 'UZ', value: '+998' },
    { no: 235, label: 'Vanuatu', code: 'VU', value: '+678' },
    { no: 236, label: 'Vatican', code: 'VA', value: '+379' },
    { no: 237, label: 'Venezuela', code: 'VE', value: '+58' },
    { no: 238, label: 'Vietnam', code: 'VN', value: '+84' },
    { no: 239, label: 'Wallis and Futuna', code: 'WF', value: '+681' },
    { no: 240, label: 'Western Sahara', code: 'EH', value: '+212' },
    { no: 241, label: 'Yemen', code: 'YE', value: '+967' },
    { no: 242, label: 'Zambia', code: 'ZM', value: '+260' },
    { no: 243, label: 'Zimbabwe', code: 'ZW', value: '+263' },

];
// const Countries = [
//     { no: 1, label: 'Afghanistan', code: 'AF', value: '+93' },
//     { no: 2, label: 'Albania', code: 'AL', value: '+355' },
//     { no: 3, label: 'Algeria', code: 'DZ', value: '+213' },
//     // { no: 4, label: 'American Samoa', code: 'AS', value: '+1684' },
//     { no: 5, label: 'Andorra', code: 'AD', value: '+376' },
//     { no: 6, label: 'Angola', code: 'AO', value: '+244' },
//     // { no: 7, label: 'Anguilla', code: 'AI', value: '+1264' },
//     { no: 8, label: 'Antarctica', code: 'AQ', value: '+672' },
//     // { no: 9, label: 'Antigua and Barbuda', code: 'AG', value: '+1268' },
//     { no: 10, label: 'Argentina', code: 'AR', value: '+54' },
//     { no: 11, label: 'Armenia', code: 'AM', value: '+374' },
//     // { no: 12, label: 'Aruba', code: 'AW', value: '+297' },
//     { no: 13, label: 'Australia', code: 'AU', value: '+61' },
//     { no: 14, label: 'Austria', code: 'AT', value: '+43' },
//     { no: 15, label: 'Azerbaijan', code: 'AZ', value: '+994' },
//     // { no: 16, label: 'Bahamas', code: 'BS', value: '+1242' },
//     // { no: 17, label: 'Bahrain', code: 'BH', value: '+973' },
//     { no: 18, label: 'Bangladesh', code: 'BD', value: '+880' },
//     // { no: 19, label: 'Barbados', code: 'BB', value: '+1246' },
//     { no: 20, label: 'Belarus', code: 'BY', value: '+375' },
//     { no: 21, label: 'Belgium', code: 'BE', value: '+32' },
//     // { no: 22, label: 'Belize', code: 'BZ', value: '+501' },
//     // { no: 23, label: 'Benin', code: 'BJ', value: '+229' },
//     // { no: 24, label: 'Bermuda', code: 'BM', value: '+1441' },
//     // { no: 25, label: 'Bhutan', code: 'BT', value: '+975' },
//     { no: 26, label: 'Bolivia', code: 'BO', value: '+591' },
//     // { no: 27, label: 'Bosnia and Herzegovina', code: 'BA', value: '+387' },
//     // { no: 28, label: 'Botswana', code: 'BW', value: '+267' },
//     { no: 29, label: 'Brazil', code: 'BR', value: '+55' },
//     // { no: 30, label: 'British Indian Ocean Territory', code: 'IO', value: '+246' },
//     // { no: 31, label: 'British Virgin Islands', code: 'VG', value: '+1284' },
//     { no: 32, label: 'Brunei', code: 'BN', value: '+673' },
//     { no: 33, label: 'Bulgaria', code: 'BG', value: '+359' },
//     // { no: 34, label: 'Burkina Faso', code: 'BF', value: '+226' },
//     // { no: 35, label: 'Burundi', code: 'BI', value: '+257' },
//     { no: 36, label: 'Cambodia', code: 'KH', value: '+855' },
//     // { no: 37, label: 'Cameroon', code: 'CM', value: '+237' },
//     { no: 38, label: 'Canada', code: 'CA', value: '+1' },
//     // { no: 39, label: 'Cape Verde', code: 'CV', value: '+238' },
//     // { no: 40, label: 'Cayman Islands', code: 'KY', value: '+1345' },
//     { no: 41, label: 'Central African Republic', code: 'CF', value: '+236' },
//     // { no: 42, label: 'Chad', code: 'TD', value: '+235' },
//     { no: 43, label: 'Chile', code: 'CL', value: '+56' },
//     { no: 44, label: 'China', code: 'CN', value: '+86' },
//     // { no: 45, label: 'Christmas Island', code: 'CX', value: '+61' },
//     // { no: 46, label: 'Cocos Islands', code: 'CC', value: '+61' },
//     { no: 47, label: 'Colombia', code: 'CO', value: '+57' },
//     // { no: 48, label: 'Comoros', code: 'KM', value: '+269' },
//     // { no: 49, label: 'Cook Islands', code: 'CK', value: '+682' },
//     { no: 50, label: 'Costa Rica', code: 'CR', value: '+506' },
//     { no: 51, label: 'Croatia', code: 'HR', value: '+385' },
//     // { no: 52, label: 'Cuba', code: 'CU', value: '+53' },
//     // { no: 53, label: 'Curacao', code: 'CW', value: '+599' },
//     // { no: 54, label: 'Cyprus', code: 'CY', value: '+357' },
//     { no: 55, label: 'Czech Republic', code: 'CZ', value: '+420' },
//     { no: 56, label: 'Democratic Republic of the Congo', code: 'CD', value: '+243' },
//     { no: 57, label: 'Denmark', code: 'DK', value: '+45' },
//     // { no: 58, label: 'Djibouti', code: 'DJ', value: '+253' },
//     // { no: 59, label: 'Dominica', code: 'DM', value: '+1767' },
//     // { no: 60, label: 'Dominican Republic', code: 'DO', value: '+1809' },
//     // { no: 61, label: 'Dominican Republic', code: 'DO', value: '+1829' },
//     // { no: 62, label: 'Dominican Republic', code: 'DO', value: '+1849' },
//     // { no: 63, label: 'East Timor', code: 'TL', value: '+670' },
//     // { no: 64, label: 'Ecuador', code: 'EC', value: '+593' },
//     { no: 65, label: 'Egypt', code: 'EG', value: '+20' },
//     // { no: 66, label: 'El Salvador', code: 'SV', value: '+503' },
//     // { no: 67, label: 'Equatorial Guinea', code: 'GQ', value: '+240' },
//     // { no: 68, label: 'Eritrea', code: 'ER', value: '+291' },
//     // { no: 69, label: 'Estonia', code: 'EE', value: '+372' },
//     // { no: 70, label: 'Ethiopia', code: 'ET', value: '+251' },
//     // { no: 71, label: 'Falkland Islands', code: 'FK', value: '+500' },
//     // { no: 72, label: 'Faroe Islands', code: 'FO', value: '+298' },
//     // { no: 73, label: 'Fiji', code: 'FJ', value: '+679' },
//     { no: 74, label: 'Finland', code: 'FI', value: '+358' },
//     { no: 75, label: 'France', code: 'FR', value: '+33' },
//     // { no: 76, label: 'French Polynesia', code: 'PF', value: '+689' },
//     // { no: 77, label: 'Gabon', code: 'GA', value: '+241' },
//     // { no: 78, label: 'Gambia', code: 'GM', value: '+220' },
//     { no: 79, label: 'Georgia', code: 'GE', value: '+995' },
//     { no: 80, label: 'Germany', code: 'DE', value: '+49' },
//     // { no: 81, label: 'Ghana', code: 'GH', value: '+233' },
//     // { no: 82, label: 'Gibraltar', code: 'GI', value: '+350' },
//     { no: 83, label: 'Greece', code: 'GR', value: '+30' },
//     // { no: 84, label: 'Greenland', code: 'GL', value: '+299' },
//     // { no: 85, label: 'Grenada', code: 'GD', value: '+1473' },
//     // { no: 86, label: 'Guam', code: 'GU', value: '+1671' },
//     // { no: 87, label: 'Guatemala', code: 'GT', value: '+502' },
//     // { no: 88, label: 'Guernsey', code: 'GG', value: '+441481' },
//     // { no: 89, label: 'Guinea', code: 'GN', value: '+224' },
//     // { no: 90, label: 'Guinea-Bissau', code: 'GW', value: '+245' },
//     // { no: 91, label: 'Guyana', code: 'GY', value: '+592' },
//     // { no: 92, label: 'Haiti', code: 'HT', value: '+509' },
//     // { no: 93, label: 'Honduras', code: 'HN', value: '+504' },
//     { no: 94, label: 'Hong Kong', code: 'HK', value: '+852' },
//     { no: 95, label: 'Hungary', code: 'HU', value: '+36' },
//     { no: 96, label: 'Iceland', code: 'IS', value: '+354' },
//     { no: 97, label: 'India', code: 'IN', value: '+91' },
//     { no: 98, label: 'Indonesia', code: 'ID', value: '+62' },
//     { no: 99, label: 'Iran', code: 'IR', value: '+98' },
//     { no: 100, label: 'Iraq', code: 'IQ', value: '+964' },
//     { no: 101, label: 'Ireland', code: 'IE', value: '+353' },
//     // { no: 102, label: 'Isle of Man', code: 'IM', value: '+441624' },
//     { no: 103, label: 'Israel', code: 'IL', value: '+972' },
//     { no: 104, label: 'Italy', code: 'IT', value: '+39' },
//     // { no: 105, label: 'Ivory Coast', code: 'CI', value: '+225' },
//     // { no: 106, label: 'Jamaica', code: 'JM', value: '+1876' },
//     { no: 107, label: 'Japan', code: 'JP', value: '+81' },
//     // { no: 108, label: 'Jersey', code: 'JE', value: '+441534' },
//     // { no: 109, label: 'Jordan', code: 'JO', value: '+962' },
//     // { no: 110, label: 'Kazakhstan', code: 'KZ', value: '+7' },
//     // { no: 111, label: 'Kenya', code: 'KE', value: '+254' },
//     // { no: 112, label: 'Kiribati', code: 'KI', value: '+686' },
//     // { no: 113, label: 'Kosovo', code: 'XK', value: '+383' },
//     // { no: 114, label: 'Kuwait', code: 'KW', value: '+965' },
//     // { no: 115, label: 'Kyrgyzstan', code: 'KG', value: '+996' },
//     { no: 116, label: 'Laos', code: 'LA', value: '+856' },
//     // { no: 117, label: 'Latvia', code: 'LV', value: '+371' },
//     // { no: 118, label: 'Lebanon', code: 'LB', value: '+961' },
//     // { no: 119, label: 'Lesotho', code: 'LS', value: '+266' },
//     // { no: 120, label: 'Liberia', code: 'LR', value: '+231' },
//     // { no: 121, label: 'Libya', code: 'LY', value: '+218' },
//     // { no: 122, label: 'Liechtenstein', code: 'LI', value: '+423' },
//     { no: 123, label: 'Lithuania', code: 'LT', value: '+370' },
//     { no: 124, label: 'Luxembourg', code: 'LU', value: '+352' },
//     { no: 125, label: 'Macau', code: 'MO', value: '+853' },
//     // { no: 126, label: 'Macedonia', code: 'MK', value: '+389' },
//     // { no: 127, label: 'Madagascar', code: 'MG', value: '+261' },
//     // { no: 128, label: 'Malawi', code: 'MW', value: '+265' },
//     { no: 129, label: 'Malaysia', code: 'MY', value: '+60' },
//     { no: 130, label: 'Maldives', code: 'MV', value: '+960' },
//     // { no: 131, label: 'Mali', code: 'ML', value: '+223' },
//     // { no: 132, label: 'Malta', code: 'MT', value: '+356' },
//     // { no: 133, label: 'Marshall Islands', code: 'MH', value: '+692' },
//     // { no: 134, label: 'Mauritania', code: 'MR', value: '+222' },
//     // { no: 135, label: 'Mauritius', code: 'MU', value: '+230' },
//     // { no: 136, label: 'Mayotte', code: 'YT', value: '+262' },
//     { no: 137, label: 'Mexico', code: 'MX', value: '+52' },
//     // { no: 138, label: 'Micronesia', code: 'FM', value: '+691' },
//     { no: 139, label: 'Moldova', code: 'MD', value: '+373' },
//     { no: 140, label: 'Monaco', code: 'MC', value: '+377' },
//     { no: 141, label: 'Mongolia', code: 'MN', value: '+976' },
//     // { no: 142, label: 'Montenegro', code: 'ME', value: '+382' },
//     // { no: 143, label: 'Montserrat', code: 'MS', value: '+1664' },
//     { no: 144, label: 'Morocco', code: 'MA', value: '+212' },
//     // { no: 145, label: 'Mozambique', code: 'MZ', value: '+258' },
//     { no: 146, label: 'Myanmar', code: 'MM', value: '+95' },
//     // { no: 147, label: 'Namibia', code: 'NA', value: '+264' },
//     // { no: 148, label: 'Nauru', code: 'NR', value: '+674' },
//     // { no: 149, label: 'Nepal', code: 'NP', value: '+977' },
//     { no: 150, label: 'Netherlands', code: 'NL', value: '+31' },
//     // { no: 151, label: 'Netherlands Antilles', code: 'AN', value: '+599' },
//     // { no: 152, label: 'New Caledonia', code: 'NC', value: '+687' },
//     { no: 153, label: 'New Zealand', code: 'NZ', value: '+64' },
//     // { no: 154, label: 'Nicaragua', code: 'NI', value: '+505' },
//     // { no: 155, label: 'Niger', code: 'NE', value: '+227' },
//     // { no: 156, label: 'Nigeria', code: 'NG', value: '+234' },
//     { no: 157, label: 'Niue', code: 'NU', value: '+683' },
//     { no: 158, label: 'North Korea', code: 'KP', value: '+850' },
//     // { no: 159, label: 'Northern Mariana Islands', code: 'MP', value: '+1670' },
//     { no: 160, label: 'Norway', code: 'NO', value: '+47' },
//     { no: 161, label: 'Oman', code: 'OM', value: '+968' },
//     { no: 162, label: 'Pakistan', code: 'PK', value: '+92' },
//     { no: 163, label: 'Palau', code: 'PW', value: '+680' },
//     { no: 164, label: 'Palestine', code: 'PS', value: '+970' },
//     // { no: 165, label: 'Panama', code: 'PA', value: '+507' },
//     // { no: 166, label: 'Papua New Guinea', code: 'PG', value: '+675' },
//     // { no: 167, label: 'Paraguay', code: 'PY', value: '+595' },
//     { no: 168, label: 'Peru', code: 'PE', value: '+51' },
//     { no: 169, label: 'Philippines', code: 'PH', value: '+63' },
//     // { no: 170, label: 'Pitcairn', code: 'PN', value: '+64' },
//     { no: 171, label: 'Poland', code: 'PL', value: '+48' },
//     { no: 172, label: 'Portugal', code: 'PT', value: '+351' },
//     { no: 173, label: 'Puerto Rico', code: 'PR', value: '+1787' },
//     { no: 174, label: 'Puerto Rico', code: 'PR', value: '+1939' },
//     { no: 175, label: 'Qatar', code: 'QA', value: '+974' },
//     { no: 176, label: 'Republic of the Congo', code: 'CG', value: '+242' },
//     // { no: 177, label: 'Reunion', code: 'RE', value: '+262' },
//     { no: 178, label: 'Romania', code: 'RO', value: '+40' },
//     { no: 179, label: 'Russia', code: 'RU', value: '+7' },
//     // { no: 180, label: 'Rwanda', code: 'RW', value: '+250' },
//     // { no: 181, label: 'Saint Barthelemy', code: 'BL', value: '+590' },
//     // { no: 182, label: 'Saint Helena', code: 'SH', value: '+290' },
//     // { no: 183, label: 'Saint Kitts and Nevis', code: 'KN', value: '+1869' },
//     // { no: 184, label: 'Saint Lucia', code: 'LC', value: '+1758' },
//     // { no: 185, label: 'Saint Martin', code: 'MF', value: '+590' },
//     // { no: 186, label: 'Saint Pierre and Miquelon', code: 'PM', value: '+508' },
//     // { no: 187, label: 'Saint Vincent and the Grenadines', code: 'VC', value: '+1784' },
//     // { no: 188, label: 'Samoa', code: 'WS', value: '+685' },
//     // { no: 189, label: 'San Marino', code: 'SM', value: '+378' },
//     // { no: 190, label: 'Sao Tome and Principe', code: 'ST', value: '+239' },
//     { no: 191, label: 'Saudi Arabia', code: 'SA', value: '+966' },
//     // { no: 192, label: 'Senegal', code: 'SN', value: '+221' },
//     // { no: 193, label: 'Serbia', code: 'RS', value: '+381' },
//     // { no: 194, label: 'Seychelles', code: 'SC', value: '+248' },
//     // { no: 195, label: 'Sierra Leone', code: 'SL', value: '+232' },
//     { no: 196, label: 'Singapore', code: 'SG', value: '+65' },
//     // { no: 197, label: 'Sint Maarten', code: 'SX', value: '+1721' },
//     { no: 198, label: 'Slovakia', code: 'SK', value: '+421' },
//     { no: 199, label: 'Slovenia', code: 'SI', value: '+386' },
//     // { no: 200, label: 'Solomon Islands', code: 'SB', value: '+677' },
//     // { no: 201, label: 'Somalia', code: 'SO', value: '+252' },
//     { no: 202, label: 'South Africa', code: 'ZA', value: '+27' },
//     { no: 203, label: 'South Korea', code: 'KR', value: '+82' },
//     // { no: 204, label: 'South Sudan', code: 'SS', value: '+211' },
//     { no: 205, label: 'Spain', code: 'ES', value: '+34' },
//     // { no: 206, label: 'Sri Lanka', code: 'LK', value: '+94' },
//     // { no: 207, label: 'Sudan', code: 'SD', value: '+249' },
//     // { no: 208, label: 'Suriname', code: 'SR', value: '+597' },
//     // { no: 209, label: 'Svalbard and Jan Mayen', code: 'SJ', value: '+47' },
//     // { no: 210, label: 'Swaziland', code: 'SZ', value: '+268' },
//     { no: 211, label: 'Sweden', code: 'SE', value: '+46' },
//     { no: 212, label: 'Switzerland', code: 'CH', value: '+41' },
//     // { no: 213, label: 'Syria', code: 'SY', value: '+963' },
//     // { no: 214, label: 'Taiwan', code: 'TW', value: '+886' },
//     // { no: 215, label: 'Tajikistan', code: 'TJ', value: '+992' },
//     // { no: 216, label: 'Tanzania', code: 'TZ', value: '+255' },
//     { no: 217, label: 'Thailand', code: 'TH', value: '+66' },
//     // { no: 218, label: 'Togo', code: 'TG', value: '+228' },
//     // { no: 219, label: 'Tokelau', code: 'TK', value: '+690' },
//     // { no: 220, label: 'Tonga', code: 'TO', value: '+676' },
//     // { no: 221, label: 'Trinidad and Tobago', code: 'TT', value: '+1868' },
//     // { no: 222, label: 'Tunisia', code: 'TN', value: '+216' },
//     { no: 223, label: 'Turkey', code: 'TR', value: '+90' },
//     // { no: 224, label: 'Turkmenistan', code: 'TM', value: '+993' },
//     // { no: 225, label: 'Turks and Caicos Islands', code: 'TC', value: '+1649' },
//     // { no: 226, label: 'Tuvalu', code: 'TV', value: '+688' },
//     // { no: 227, label: 'U.S. Virgin Islands', code: 'VI', value: '+1340' },
//     // { no: 228, label: 'Uganda', code: 'UG', value: '+256' },
//     // { no: 229, label: 'Ukraine', code: 'UA', value: '+380' },
//     { no: 230, label: 'United Arab Emirates', code: 'AE', value: '+971' },
//     { no: 231, label: 'United Kingdom', code: 'GB', value: '+44' },
//     { no: 232, label: 'United States', code: 'US', value: '+1' },
//     // { no: 233, label: 'Uruguay', code: 'UY', value: '+598' },
//     // { no: 234, label: 'Uzbekistan', code: 'UZ', value: '+998' },
//     // { no: 235, label: 'Vanuatu', code: 'VU', value: '+678' },
//     // { no: 236, label: 'Vatican', code: 'VA', value: '+379' },
//     // { no: 237, label: 'Venezuela', code: 'VE', value: '+58' },
//     // { no: 238, label: 'Vietnam', code: 'VN', value: '+84' },
//     // { no: 239, label: 'Wallis and Futuna', code: 'WF', value: '+681' },
//     // { no: 240, label: 'Western Sahara', code: 'EH', value: '+212' },
//     // { no: 241, label: 'Yemen', code: 'YE', value: '+967' },
//     // { no: 242, label: 'Zambia', code: 'ZM', value: '+260' },
//     // { no: 243, label: 'Zimbabwe', code: 'ZW', value: '+263' },

// ];

export default Countries